[build]
command = "pnpm run build"
publish = "dist"

[build.processing.css]
bundle = true
minify = true
[build.processing.js]
bundle = true
minify = true

[[redirects]]
from = "/"
to = "/projects/1"
status = 301
force = true
