name: ci

on:
  pull_request:
    branches:
      - main
      - prod
  push:
    branches:
     - main

jobs:
  ci:
    env:
      # to tell pnpm this is a CI environment
      CI: true
      ASTRO_TELEMETRY_DISABLED: true

    name: ci
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Check formatting
        run: pnpm run format:check
      - name: Lint
        run: pnpm run lint:ci
      - name: Run verify types
        run: pnpm run verify-types
        # - name: Run test with coverage
        #   run: pnpm run coverage
